### PR TITLE
move descriptors to correct namespace

### PR DESCRIPTION
**Pull request by jaapio**

### CODE REVIEW

**Comment by mvriel** [comment]
Should I wait reviewing this one until #44 and #53 is merged?

**Comment by jaapio** [comment]
You could review this, I will update the other pr's

**Comment by mvriel** [comment]
Can you merge develop into this? I cannot merge this after the review

**Comment by mvriel** [comment]
Review complete, did not see anything odd. I might have missed one or two places where it should have been done but let's do a complete review after the refactoring is complete. Once develop is merged I can merge this PR

**Comment by jaapio** [comment]
check, rebased it

**Pull request merged**
