### PR TITLE
[WIP] Upgrade PHP-Parser to >=1.0

### PR DESCRIPTION
**Pull request by theofidry**
@mvriel I'm trying to upgrade the PHP-Parser dependency like mentioned in #34.

As long as the develop branch is not merged to master, [DunglasApiBundle](https://github.com/dunglas/DunglasApiBundle) requires `nikic-php-parser < 1.0` whereas [PsyshBundle](https://github.com/theofidry/PsyshBundle) requires `nikic-php-parser >= 1.0` as mentioned in theofidry/PsyshBundle#2.

For now I updated the packages name using aliases to avoid to have to change too much code. However I'm stuck for the `use phpDocumentor\Event\DebugEvent;` which no longer exists and I don't know by what it should be replaced.

cc @dunglas

### CODE REVIEW

**Comment by theofidry** [comment]
ping @mvriel: could it be possible to have some help or the next version if for soon?

**Comment by mvriel** [comment]
Hello @theofidry, I seem to have missed your original ping. I will take a look at this this evening

**Comment by theofidry** [comment]
Thanks

**Comment by cebe** [comment]
Note that requiring a new major version of a dependency is a BC break in some way so I am not sure if this should go into a minor release.

**Comment by mvriel** [comment]
Well, perhaps a BC break is not necessary for this to work. In this PR I mostly see that the namespaced names are introduced but PHP-Parser claims to support their legacy names (without namespaces) until 2.0.

Do you know if there are other changes? Or can we re-use PHP-Parser's legacy naming?

I agree with @cebe that, because this is a library, it may be inconvenient to change this without BC compatibility (some people are still on 0.9.4 perhaps?).

**Comment by theofidry** [comment]
Indeed there is no reason to use the `0.9.4` version so I redid it based on the `1.0.7` version. Well, the only need is to upgrade the `nikic/php-parser` version and I don't think that it should cause any BC break in this library API.

**Comment by theofidry** [comment]
The changes I have made are really basic for now.

The main issue at the moment is the `Event` system which is broken because of undefined classes. Then it comes down to:

* check if any function changed
* make the test pass
* check for the use of class names in string comparison

**Comment by mvriel** [comment]
Are you sure these changes are compatible with 0.9.4? People who currently use PHP-Parser 0.9.4 should still be able to use this library (and thus the composer.json should link to 0.9.4 as minimum)

**Comment by theofidry** [comment]
No I did not check that and it is very likely that they are not compatible. But regardless of how we proceed having a version with a more recent version of the php-parser is a must.

**Comment by mvriel** [comment]
If they are incompatible than we cannot integrate this in version 1.x because that is a rather large BC break (everyone who uses PHP-Parser 0.9.4 can no longer use the Reflection package).

We are currently working on a version 2.0 on the develop branch that will include the PHP-Parser 1.0 and higher

**Comment by theofidry** [comment]
Yes but when will it be released? I don't mind waiting for the version 2.0, but if it's take another two or three months maybe it would be faster to make a release just for the php-parser dependency.

**Comment by theofidry** [comment]
Another way would be to allow both PHP-Parser version. This way it can still be released under the 1.X tag and should not cause any trouble for people still on PHP-Parser 0.9.

**Comment by mvriel** [comment]
We want to release the new component as soon as possible; I expect this somewhere in the coming month, maybe two.

If it is possible to serve both releases than I see no problem; we are unable to have a bc break of this kind in 1.x

**Comment by theofidry** [comment]
Well, this should be doable since the only BC break it may cause is the change of the dependency, which is handled if we proceed like that.

Since the next version is coming soon, the real interest of this PR really depends of the amount of work required to achieve the wished result.

For now, the only thing I'm really not sure is how the Event system works: I've got lots of use of non existing event classes. Can you enlighten me on this?

**Comment by mvriel** [comment]
Heh, this is actually a bit of a concession towards phpDocumentor when the two were still combined and is considered legacy (and kept for BC purposes).

When you pass a Symfony EventDispatcher to the reflectors than `reflection.docblock-extraction.post` event is triggered with the `\phpDocumentor\Reflection\Event\PostDocBlockExtractionEvent` event class; this can be used to do post-processing and filtering on the DocBlock during reflection. It was used to validate the DocBlocks but that mechanism has since moved.

In the next version of Reflection those events will no longer be called

**Comment by mvriel** [comment]
Hello @theofidry,

My apologies for not coming back to you sooner. After some discussion within the team we ultimately decided that the BC break is a necessary evil since not doing it limits us in how many bugs we can fix and to allow support for higher PHP versions.

Unfortunately I lost track of this PR, my apologies for that, and one of the team members did the upgrade and I just merged it.

So the changes are currently included in the master branch, I will be tagging and releasing a new version somewhere this weekend.

I do offer an apology; it would have been fairer to come back to you and merge your PR. I hope this helps and let me know if you require more information or if something is still off

**Comment by theofidry** [comment]
Hi @mvriel, no worries I couldn't find the time to finish this PR either ;)

I'll try it out as you'll tag a new version :)

**Pull request closed without merging**
