### PR TITLE
#241 Add start and end file positions to method locations

### PR DESCRIPTION
**Pull request by LeoVie**
This solves #241

### CODE REVIEW

**Comment by LeoVie** [comment]
Saw my fault, this should be green now. :)

**Comment by LeoVie** [comment]
I don't really get, why this is still red.

There seem to be some pgp key issues on the windows runners https://github.com/phpDocumentor/Reflection/runs/5751208572?check_suite_focus=true

And I don't know, if the issues on the ubuntu runners are related to my changes or if they are occuring somehow random: https://github.com/phpDocumentor/Reflection/runs/5751214156?check_suite_focus=true

**Comment by jaapio** [comment]
Please ignore the windows builds for now... we do have this issue on all repo's :-(

**Comment by LeoVie** [comment]
Okay. Can you give me a hint about the failing ubuntu runs? For example this one: https://github.com/phpDocumentor/Reflection/runs/5751214156?check_suite_focus=true

This seems to be related to the lowest composer dependencies, because here the error does not occur: https://github.com/phpDocumentor/Reflection/runs/5751207400?check_suite_focus=true

If I'm interpreting this right, this has nothing to do with changes of this pull request. Is this right?

**Comment by jaapio** [comment]
Ah, sorry about that, I left a comment a bit too early, as I had to go for lunch. 

You may ignore all of this, I pushed a change yesterday to do some more boundary testing on component constraints. And it seems that we are not strict enough for some of the dependencies. The allowed range should be more narrow. 

I will fix that in a new PR. Your changes are looking good!.

**Comment by jaapio** [comment]
@LeoVie was this all what's needed for your feature request?

**Comment by LeoVie** [comment]
@jaapio In this repository, yes. I will create a pull request in the original issue at https://github.com/phpDocumentor/phpDocumentor/issues/3154 for the other required changes, once there is a new build of phpDocumentor/Reflection.

Thanks for merging! :)

**Pull request merged**
