### PR TITLE
Php parser upgrade

### PR DESCRIPTION
**Pull request by jaapio**
Tests are passing. I still need to test this with the phpdocumentor master branch

### CODE REVIEW

**Comment by mvriel** [comment]
@jaapio it seems that you updated all dependencies and for one of the dependencies (symfony/filesystem) a new major was imported that breaks compatibility with PHP 5.3 and 5.4. Can you do a composer update with just PHP-Parser?

**Comment by jaapio** [comment]
sorry about that, Think I made a typo in the update command.

**Comment by mvriel** [comment]
Hmm .. apparently now something else is going wrong: https://travis-ci.org/phpDocumentor/Reflection/jobs/108110521

**Comment by jaapio** [comment]
Think I found it again. only 5.3.3 is failing

**Comment by mvriel** [comment]
:+1:

**Comment by mvriel** [comment]
Awesome!

**Pull request merged**
