### PR TITLE
Docs: fix typo

### PR DESCRIPTION
**Pull request by jrfnl**
Came across this while testing a new sniff I'm working on 😁

### CODE REVIEW

**Comment by jrfnl** [comment]
Looks like your coding standards would prefer to remove the tag (which wasn't flagged before due to the typo). Shall I ?

**Review by jaapio — APPROVED** [review]

**Review by jaapio — CHANGES_REQUESTED** [review]
This tag can be removed entirely, as the native return type already describes the type.

**Comment by jrfnl** [comment]
@jaapio Done ;-)

**Review by jaapio — APPROVED** [review]

**Comment by jaapio** [comment]
Thanks!

**Pull request merged**
