### PR TITLE
Feature/remove tags and types

### PR DESCRIPTION
**Pull request by jaapio**
This pr shall be reviewed after #41.

In this PR I removed all Tag and Type code that was not used. anymore. More will follow when the builders are refactored.

### CODE REVIEW

**Comment by mvriel** [comment]
@jaapio can you merge develop first? :)

**Comment by jaapio** [comment]
Rebased

**Comment by mvriel** [comment]
I see you removed the Example Finder; that functionality in that class is necessary for the `@example` tag implementation. We might reintroduce it in another form but I am not sure yet how this fits in the new architecture exactly

**Comment by mvriel** [comment]
No other feedback, the rest is good to go

**Comment by mvriel** [comment]
ExampleFinder will be imported into the Reflection DocBlock package

**Pull request merged**
