### PR TITLE
Allow PHP 8.4

### PR DESCRIPTION
**Pull request by francoism90**
I'm keep getting this message on PHP 8.4 testing:

```bash
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.
  Problem 1
    - phpdocumentor/reflection is locked to version 6.0.0 and an update of this package was not requested.
    - phpdocumentor/reflection 6.0.0 requires php 8.1.*|8.2.*|8.3.* -> your php version (8.4.1) does not satisfy that requirement.
  Problem 2
    - spatie/laravel-data is locked to version 4.11.1 and an update of this package was not requested.
    - phpdocumentor/reflection 6.0.0 requires php 8.1.*|8.2.*|8.3.* -> your php version (8.4.1) does not satisfy that requirement.
    - spatie/laravel-data 4.11.1 requires phpdocumentor/reflection ^6.0 -> satisfiable by phpdocumentor/reflection[6.0.0].
```
Is there any reason why PHP versions are fixed defined? :)

### CODE REVIEW

**Comment by jaapio** [comment]
The reason why it because this library is bound to the internals of php. We want to make sure we test everything before we allow an upgrade. 

It's planned to add php 8.4 support. But I want to make sure it works.  I didn't have the time yet so that's why I don't want to merge your pr right away.

**Comment by jaapio** [comment]
I added php 8.4 in #640, thanks for your reminder!

**Comment by francoism90** [comment]
@jaapio Thanks, hopefully my PR was a bit useful. :)

I couldn't understand how to add the PHP 8.4 test.

**Comment by jaapio** [comment]
It was at least a reminder for me that people are waiting for this. So thank you for that. 
Our pipelines do automatically pick up new php versions.

**Pull request closed without merging**
