### PR TITLE
bump phpstan

### PR DESCRIPTION
**Pull request by orklah**
This will bump phpstan to last version. I create in draft to check some fixes I made

### CODE REVIEW

**Comment by orklah** [comment]
@jaapio CI for pull request seems broken here too.

**Comment by jaapio** [comment]
Thanks for pointing this out. It should be fixed right now.

**Comment by orklah** [comment]
@jaapio looks like it's still broken. An issue in Phive apparently

**Comment by jaapio** [comment]
Now it is working :-) but seems that some test are broken

**Comment by orklah** [comment]
> Now it is working :-) but seems that some test are broken

Thanks for fixing the build!

About tests. Every broken test seems wrong to me. They're all variations of the same error: a non-object was pushed in findMatching.

The issue is that findMatching will give that to match() which will only return meaningful result if an object is given.

I added a param hint object to every match() and to findMatching, that's why we have those errors.

If you agree, I propose to drop all those tests but one who will check if we get a TypeError when we push something that is not an object.

**Comment by jaapio** [comment]
It could be that those tests are not correctly, but dropping them is a bit too much I think. Because they serve a purpose. One of the testcases `\phpDocumentor\Reflection\Php\Factory\Function_Test::testCreateWithParameters` for example is using `params` which should be an object but the tests is defining a string. So I think we need to fix that instead of dropping the tests.

**Comment by orklah** [comment]
mmh ok. I tried to take a look but I don't really know what I'm doing. Do you mind if i marked them as skipped until they're fixed by someone else (or possibly me when I'll know this library better?)

**Comment by jaapio** [comment]
Sure! please mark them as skipped and @mvriel or I will have a look at them.

**Comment by orklah** [comment]
This is ready for review. I suppose you'll want to check for BC too :)

**Pull request closed without merging**
